// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:4eed9e8b-deb9-4d5c-8c9b-e54d0ec359b1",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_vEjxSPgda",
    "aws_user_pools_web_client_id": "hvdhk0coj96pbcs0c3ulhfi5m",
    "oauth": {}
};


export default awsmobile;
